services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine

    ports:
      - "127.0.0.1:15672:15672"
      - "127.0.0.1:5672:5672"

    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/mnesia

    networks:
      - work-queues

volumes:
  rabbitmq-data:

networks:
  work-queues:
    driver: bridge